PRAGMA foreign_keys=OFF;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS CCY_XRATES(DT TEXT NOT NULL,CCY TEXT NOT NULL,VAL TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS "DEF_CCY_XRATES"(
  LAST_DATE TEXT,
  CCY TEXT,
  VAL TEXT,
  "DESC" TEXT
);

CREATE VIEW IF NOT EXISTS XRATES AS
SELECT
  CCY_XRATES.DT AS DT,
  CCY_XRATES_DOUB.CCY AS FROM_CCY,
  ROUND(CCY_XRATES.VAL/CCY_XRATES_DOUB.VAL,4) AS XRATE,
  CCY_XRATES.CCY AS TO_CCY
FROM
  CCY_XRATES,
  CCY_XRATES AS CCY_XRATES_DOUB
WHERE
  CCY_XRATES.DT = CCY_XRATES_DOUB.DT
ORDER BY
  CCY_XRATES.DT,
  CCY_XRATES.CCY ASC
/* XRATES(DT,FROM_CCY,XRATE,TO_CCY) */;

CREATE VIEW IF NOT EXISTS LAST_XRATES AS
SELECT
  CCY_XRATES.DT AS DT,
  CCY_XRATES_DOUB.CCY AS FROM_CCY,
  ROUND(CCY_XRATES.VAL/CCY_XRATES_DOUB.VAL,4) AS XRATE,
  CCY_XRATES.CCY AS TO_CCY
FROM
  CCY_XRATES,
  CCY_XRATES AS CCY_XRATES_DOUB
WHERE
  CCY_XRATES.DT = CCY_XRATES_DOUB.DT AND
  CCY_XRATES.DT = (SELECT MAX(DT) FROM CCY_XRATES)
ORDER BY
  CCY_XRATES_DOUB.CCY
/* LAST_XRATES(DT,FROM_CCY,XRATE,TO_CCY) */;
COMMIT;
