CREATE TABLE COUNTRY_CODES(
  "Code" TEXT,
  "Country name (using title case)" TEXT,
  "Year" TEXT,
  "ccTLD" TEXT,
  "ISO 3166-2" TEXT,
  "Notes" TEXT
);

CREATE TABLE CURRENCY_CODES(
  "Code" TEXT,
  "Num" TEXT,
  "D" TEXT,
  "Currency" TEXT,
  "Locations listed for this currency" TEXT
);

CREATE TABLE CCY_XRATES(DT TEXT,CCY,VAL TEXT);

CREATE VIEW XRATES AS
SELECT
  CCY_XRATES.DT AS DT,
  CCY_XRATES_DOUB.CCY AS FROM_CCY,
  ROUND(CCY_XRATES.VAL/CCY_XRATES_DOUB.VAL,4) AS XRATE,
  CCY_XRATES.CCY AS TO_CCY
FROM
  CCY_XRATES,
  CCY_XRATES AS CCY_XRATES_DOUB
WHERE
  CCY_XRATES.DT = CCY_XRATES_DOUB.DT
ORDER BY
  CCY_XRATES.DT,
  CCY_XRATES.CCY ASC;

CREATE VIEW LAST_XRATES AS
SELECT
  CCY_XRATES.DT AS DT,
  CCY_XRATES_DOUB.CCY AS FROM_CCY,
  ROUND(CCY_XRATES.VAL/CCY_XRATES_DOUB.VAL,4) AS XRATE,
  CCY_XRATES.CCY AS TO_CCY
FROM
  CCY_XRATES,
  CCY_XRATES AS CCY_XRATES_DOUB
WHERE
  CCY_XRATES.DT = CCY_XRATES_DOUB.DT AND
  CCY_XRATES.DT = (SELECT MAX(DT) FROM CCY_XRATES)
ORDER BY
  CCY_XRATES_DOUB.CCY;

CREATE TABLE IF NOT EXISTS "DEF_CCY_XRATES"(
  LAST_DATE TEXT,
  CCY TEXT,
  VAL TEXT,
  "DESC" TEXT
);

